[env:uno_r4_wifi]
platform  = renesas-ra
board     = uno_r4_wifi
framework = arduino

monitor_speed = 9600
upload_speed  = 115200

build_flags =
    -std=c++17
    -Wall
    -Wextra
    -DSMARTPILLOW_VERSION=\"0.1.0\"
    -Wl,-u,_printf_float
    -DLOG_LEVEL=1

lib_deps =
    bogde/HX711@^0.7.5
    bblanchon/ArduinoJson@^7.0.0

[env:uno_r4_wifi_debug]
extends      = env:uno_r4_wifi
build_flags  =
    ${env:uno_r4_wifi.build_flags}
    -DLOG_LEVEL=0
    -g
    -Og