; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
upload_speed  = 115200
build_flags =
    -std=c++17
    -Wall
    -Wextra
    -DSMARTPILLOW_VERSION=\"0.1.0\"
    -Wl,-u,_printf_float
    -DLOG_LEVEL=1
lib_deps =
    bogde/HX711@^0.7.5
    bblanchon/ArduinoJson@^7.0.0

[env:uno_r4_wifi_debug]
extends      = env:uno_r4_wifi
build_flags  =
    ${env:uno_r4_wifi.build_flags}
    -DLOG_LEVEL=0
    -g
    -Og

[env:native_test]
platform  = native
test_framework = unity
build_flags =
    -std=c++17
    -DUNIT_TEST
    -DLOG_LEVEL=3
    -DUNITY_EXCLUDE_UNITY_CONFIG_H
    -I test
lib_deps =
    throwtheswitch/Unity@^2.5.2
build_src_filter = -<*>
